import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "es" | "th" | "de";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};

const translations = {
  en: {
    // Navigation
    "nav.diveSites": "Dive Sites",
    "nav.destinations": "Destinations",
    "nav.activities": "Activities",
    "nav.accommodations": "Accommodations",
    "nav.businessDirectory": "Business Directory",
    "nav.planTrip": "Plan Your Trip",
    
    // Hero
    "hero.title": "Discover",
    "hero.subtitle": "Koh Tao",
    "hero.description": "Your ultimate guide to Thailand's tropical diving paradise. Explore pristine beaches, world-class dive sites, and unforgettable adventures.",
    "hero.searchPlaceholder": "Search dive sites, beaches, activities...",
    "hero.explore": "Explore",
    "hero.viewDiveSites": "View Dive Sites",
    "hero.stats.diveSites": "Dive Sites",
    "hero.stats.beaches": "Beaches",
    "hero.stats.restaurants": "Restaurants",
    "hero.stats.daysOfSun": "Days of Sun",
    
    // Dive Sites
    "diveSites.title": "World-Class Dive Sites",
    "diveSites.description": "Explore over 30 incredible dive sites around Koh Tao, from beginner-friendly reefs to advanced pinnacles",
    "diveSites.featured": "Featured Dive Site",
    "diveSites.chumphonPinnacle": "Chumphon Pinnacle",
    "diveSites.chumphonDescription": "One of Koh Tao's most famous dive sites, known for its rich marine life and strong currents. Encounter whale sharks, barracudas, and giant groupers.",
    "diveSites.bookDiveTrip": "Book a Dive Trip",
    "diveSites.viewDetails": "View Details",
    "diveSites.exploreAll": "Explore All Dive Sites",
    "diveSites.difficulty.advanced": "Advanced",
    "diveSites.difficulty.intermediate": "Intermediate",
    "diveSites.difficulty.beginner": "Beginner",
    "diveSites.depth": "Depth",
    "diveSites.marineLife": "Marine Life",
    
    // Destinations
    "destinations.title": "Must-Visit Destinations",
    "destinations.description": "From pristine beaches to breathtaking viewpoints, discover Koh Tao's most stunning locations",
    "destinations.getDirections": "Get Directions",
    "destinations.mapTitle": "Explore with Interactive Map",
    "destinations.mapDescription": "Navigate Koh Tao with our comprehensive map featuring all dive sites, beaches, restaurants, and activities",
    "destinations.openMap": "Open Interactive Map",
    "destinations.type.beach": "Beach",
    "destinations.type.viewpoint": "Viewpoint",
    
    // Activities
    "activities.title": "Activities & Experiences",
    "activities.description": "Book unforgettable experiences and adventures on Koh Tao",
    "activities.bookNow": "Book Now",
    "activities.specialTitle": "Early Bird Special",
    "activities.specialDescription": "Book your diving course or activity 7 days in advance and get 15% off",
    "activities.viewAllDeals": "View All Deals",
    
    // Accommodations
    "accommodations.title": "Accommodations",
    "accommodations.description": "Find the perfect place to stay on Koh Tao, from budget hostels to luxury beachfront resorts",
    "accommodations.featured": "Featured Stay",
    "accommodations.bookNow": "Book Now",
    "accommodations.viewDetails": "View Details",
    "accommodations.exploreAll": "Explore All Accommodations",
    "accommodations.type.resort": "Resort",
    "accommodations.type.villa": "Villa",
    "accommodations.type.bungalow": "Bungalow",
    "accommodations.type.hostel": "Hostel",
    "accommodations.pricePerNight": "/night",
    
    // Business Directory
    "businessDirectory.title": "Business Directory",
    "businessDirectory.description": "Discover restaurants, shops, dive centers, and services across Koh Tao",
    "businessDirectory.all": "All",
    "businessDirectory.restaurants": "Restaurants",
    "businessDirectory.diveShops": "Dive Shops",
    "businessDirectory.shopping": "Shopping",
    "businessDirectory.cafes": "Cafés",
    "businessDirectory.details": "Details",
    "businessDirectory.contact": "Contact",
    "businessDirectory.viewAll": "View All Businesses",
    
    // Newsletter
    "newsletter.title": "Stay Updated",
    "newsletter.description": "Get the latest news, exclusive deals, and travel tips delivered to your inbox",
    "newsletter.placeholder": "Enter your email address",
    "newsletter.subscribe": "Subscribe",
    "newsletter.subscribers": "Join over 5,000 travelers exploring Koh Tao",
    
    // Footer
    "footer.explore": "Explore",
    "footer.activities": "Activities",
    "footer.plan": "Plan",
    "footer.about": "About",
    "footer.backToTop": "Back to Top",
    "footer.copyright": "© 2025 Koh Tao Guide. All rights reserved. Built with love for travelers.",
    "footer.description": "Your comprehensive travel companion for exploring Thailand's tropical paradise.",
    "footer.link.diveSites": "Dive Sites",
    "footer.link.beaches": "Beaches",
    "footer.link.viewpoints": "Viewpoints",
    "footer.link.restaurants": "Restaurants",
    "footer.link.nightlife": "Nightlife",
    "footer.link.divingCourses": "Diving Courses",
    "footer.link.boatTours": "Boat Tours",
    "footer.link.snorkeling": "Snorkeling",
    "footer.link.bikeRentals": "Bike Rentals",
    "footer.link.islandHopping": "Island Hopping",
    "footer.link.accommodations": "Accommodations",
    "footer.link.gettingThere": "Getting There",
    "footer.link.bestTimeToVisit": "Best Time to Visit",
    "footer.link.travelTips": "Travel Tips",
    "footer.link.weather": "Weather",
    "footer.link.aboutUs": "About Us",
    "footer.link.contact": "Contact",
    "footer.link.businessListings": "Business Listings",
    "footer.link.advertise": "Advertise",
    "footer.link.termsPrivacy": "Terms & Privacy",
    "footer.address": "Koh Tao, Surat Thani, Thailand",
    
    // Toast Messages
    "toast.gettingDirections": "Getting Directions",
    "toast.openingMap": "Opening map",
    "toast.interactiveMap": "Interactive Map",
    "toast.loadingMap": "Loading interactive map of Koh Tao...",
    "toast.bookingActivity": "Booking Activity",
    "toast.openingBooking": "Opening booking for",
    "toast.specialDeals": "Special Deals",
    "toast.loadingDeals": "Loading exclusive offers and discounts...",
    "toast.bookAccommodation": "Book Accommodation",
    "toast.openingAccommodation": "Opening booking for",
    "toast.openingDetails": "Opening detailed information...",
    "toast.allAccommodations": "All Accommodations",
    "toast.loadingAccommodations": "Loading complete accommodation catalog...",
    "toast.contactBusiness": "Contact Business",
    "toast.openingContact": "Opening contact options for",
    "toast.allBusinesses": "All",
    "toast.loadingBusinesses": "Loading complete directory...",
    "toast.success": "Success!",
    "toast.subscribed": "Thank you for subscribing to our newsletter.",
    
    // Destinations Data
    "destinations.saireeBeach.name": "Sairee Beach",
    "destinations.saireeBeach.description": "The longest beach on Koh Tao, perfect for swimming and sunset views",
    "destinations.johnSuwan.name": "John-Suwan Viewpoint",
    "destinations.johnSuwan.description": "Breathtaking 360° panoramic views of the island and surrounding sea",
    "destinations.sharkBay.name": "Shark Bay",
    "destinations.sharkBay.description": "Secluded bay known for blacktip reef sharks and excellent snorkeling",
    "destinations.mangoViewpoint.name": "Mango Viewpoint",
    "destinations.mangoViewpoint.description": "Popular viewpoint with stunning vistas and a relaxed atmosphere",
    "destinations.nangYuanIsland.name": "Nang Yuan Island",
    "destinations.nangYuanIsland.description": "Three small islets connected by a sandbar, famous for pristine beaches and excellent snorkeling",
    "destinations.tanoteBay.name": "Tanote Bay",
    "destinations.tanoteBay.description": "Crystal-clear waters and vibrant coral reefs, perfect for snorkeling and diving enthusiasts",
    "destinations.saiNuanBeach.name": "Sai Nuan Beach",
    "destinations.saiNuanBeach.description": "Tranquil beach with soft white sands and clear waters, ideal for swimming and relaxation",
    "destinations.aowLeukBeach.name": "Aow Leuk Beach",
    "destinations.aowLeukBeach.description": "Clear waters and abundant marine life make this a popular spot for snorkeling",
    "destinations.watKohTao.name": "Wat Koh Tao",
    "destinations.watKohTao.description": "Wat Koh Charoen Santi Dhamma - A serene Buddhist sanctuary founded in 1977. Nestled in the heart of the island, this temple offers visitors a unique glimpse into spiritual practices and Buddhist teachings in a peaceful, tranquil setting",
    "destinations.activity.swimming": "Swimming",
    "destinations.activity.snorkeling": "Snorkeling",
    "destinations.activity.beachBars": "Beach Bars",
    "destinations.activity.photography": "Photography",
    "destinations.activity.sunsetWatching": "Sunset Watching",
    "destinations.activity.hiking": "Hiking",
    "destinations.activity.wildlifeWatching": "Wildlife Watching",
    "destinations.activity.relaxation": "Relaxation",
    "destinations.activity.sunriseViews": "Sunrise Views",
    "destinations.activity.islandHopping": "Island Hopping",
    "destinations.activity.diving": "Diving",
    "destinations.activity.culturalExploration": "Cultural Exploration",
    "destinations.activity.meditation": "Meditation",
    
    // Activities Data
    "activities.divingCourses.title": "Diving Courses",
    "activities.divingCourses.description": "From beginner to professional levels",
    "activities.divingCourses.feature.padi": "PADI Certified",
    "activities.divingCourses.feature.deposit": "10% Deposit Booking",
    "activities.divingCourses.feature.instructors": "Expert Instructors",
    "activities.boatTours.title": "Boat Tours",
    "activities.boatTours.description": "Island hopping and snorkeling trips",
    "activities.boatTours.feature.fullDay": "Full Day Tours",
    "activities.boatTours.feature.snorkelGear": "Snorkeling Gear",
    "activities.boatTours.feature.lunch": "Lunch Included",
    "activities.bikeRentals.title": "Bike Rentals",
    "activities.bikeRentals.description": "Explore the island at your own pace",
    "activities.bikeRentals.feature.vehicles": "Scooters & Motorcycles",
    "activities.bikeRentals.feature.rates": "Daily & Weekly Rates",
    "activities.bikeRentals.feature.helmet": "Helmet Included",
    "activities.foodTours.title": "Food Tours",
    "activities.foodTours.description": "Taste authentic Thai cuisine",
    "activities.foodTours.feature.restaurants": "Local Restaurants",
    "activities.foodTours.feature.streetFood": "Street Food",
    "activities.foodTours.feature.cookingClasses": "Cooking Classes",
    "activities.eventsParties.title": "Events & Parties",
    "activities.eventsParties.description": "Beach parties and cultural events",
    "activities.eventsParties.feature.fullMoon": "Full Moon Parties",
    "activities.eventsParties.feature.liveMusic": "Live Music",
    "activities.eventsParties.feature.fireShows": "Fire Shows",
    "activities.activityCalendar.title": "Activity Calendar",
    "activities.activityCalendar.description": "Plan your perfect schedule",
    "activities.activityCalendar.feature.events": "Upcoming Events",
    "activities.activityCalendar.feature.book": "Book in Advance",
    "activities.activityCalendar.feature.deals": "Special Deals",
    
    // Accommodations Data
    "accommodations.oceanView.name": "Ocean View Resort",
    "accommodations.oceanView.description": "Experience luxury beachfront living with world-class amenities and stunning sunsets",
    "accommodations.taoBeach.name": "Tao Beach Resort",
    "accommodations.taoBeach.description": "Beachfront resort with stunning ocean views and easy access to dive shops",
    "accommodations.diveInn.name": "Dive Inn Bungalows",
    "accommodations.diveInn.description": "Budget-friendly bungalows perfect for divers, close to dive sites",
    "accommodations.luxuryVilla.name": "Luxury Beach Villa",
    "accommodations.luxuryVilla.description": "Premium beachfront villa with private access and full amenities",
    "accommodations.backpackerHostel.name": "Backpacker Hostel",
    "accommodations.backpackerHostel.description": "Friendly hostel atmosphere with shared dorms and common areas",
    "accommodations.location.saireeBeach": "Sairee Beach",
    "accommodations.location.chalokBaanKao": "Chalok Baan Kao",
    "accommodations.location.maeHaad": "Mae Haad",
    "accommodations.amenity.pool": "Pool",
    "accommodations.amenity.restaurant": "Restaurant",
    "accommodations.amenity.wifi": "WiFi",
    "accommodations.amenity.ac": "AC",
    "accommodations.amenity.fan": "Fan",
    "accommodations.amenity.sharedBathroom": "Shared Bathroom",
    "accommodations.amenity.privateBeach": "Private Beach",
    "accommodations.amenity.kitchen": "Kitchen",
    "accommodations.amenity.sharedKitchen": "Shared Kitchen",
    "accommodations.amenity.commonArea": "Common Area",
    
    // Business Directory Data
    "businesses.saireeBeachRestaurant.name": "Sairee Beach Restaurant",
    "businesses.saireeBeachRestaurant.description": "Fresh seafood and Thai cuisine with ocean views",
    "businesses.diveShopPro.name": "Dive Shop Pro",
    "businesses.diveShopPro.description": "Full-service dive center with equipment rental and courses",
    "businesses.islandMarket.name": "Island Market",
    "businesses.islandMarket.description": "Local market with souvenirs, clothing, and essentials",
    "businesses.sunsetCafe.name": "Sunset Café",
    "businesses.sunsetCafe.description": "Cozy café with coffee, smoothies, and light meals",
    "businesses.thaiMassageSpa.name": "Thai Massage Spa",
    "businesses.thaiMassageSpa.description": "Traditional Thai massage and spa services",
    "businesses.beachBarGrill.name": "Beach Bar & Grill",
    "businesses.beachBarGrill.description": "Relaxed beachside dining with cocktails and BBQ",
    "businesses.diveGearStore.name": "Dive Gear Store",
    "businesses.diveGearStore.description": "Professional dive equipment and accessories",
    "businesses.organicJuiceBar.name": "Organic Juice Bar",
    "businesses.organicJuiceBar.description": "Fresh juices, smoothie bowls, and healthy snacks",
    "businesses.location.saireeBeach": "Sairee Beach",
    "businesses.location.maeHaad": "Mae Haad",
    "businesses.location.chalokBaanKao": "Chalok Baan Kao",
    "businesses.category.restaurant": "Restaurant",
    "businesses.category.diveShop": "Dive Shop",
    "businesses.category.shopping": "Shopping",
    "businesses.category.cafe": "Café",
    "businesses.category.spa": "Spa",
    
    // Reviews
    "reviews.customerReviews": "Customer Reviews",
    "reviews.reviews": "reviews",
    "reviews.writeReview": "Write a Review",
    "reviews.yourName": "Your Name",
    "reviews.namePlaceholder": "Enter your name",
    "reviews.rating": "Rating",
    "reviews.comment": "Comment",
    "reviews.commentPlaceholder": "Share your experience...",
    "reviews.submitReview": "Submit Review",
    "reviews.cancel": "Cancel",
    "reviews.thankYou": "Thank You!",
    "reviews.reviewSubmitted": "Your review has been submitted successfully.",
    "reviews.noReviews": "No reviews yet. Be the first to review!",
    "reviews.error": "Error",
    "reviews.fillAllFields": "Please fill in all fields.",
    "destinations.viewDetails": "View Details",
  },
  es: {
    // Navigation
    "nav.diveSites": "Sitios de Buceo",
    "nav.destinations": "Destinos",
    "nav.activities": "Actividades",
    "nav.accommodations": "Alojamientos",
    "nav.businessDirectory": "Directorio",
    "nav.planTrip": "Planificar Viaje",
    
    // Hero
    "hero.title": "Descubre",
    "hero.subtitle": "Koh Tao",
    "hero.description": "Tu guía definitiva del paraíso tropical de buceo de Tailandia. Explora playas prístinas, sitios de buceo de clase mundial y aventuras inolvidables.",
    "hero.searchPlaceholder": "Buscar sitios de buceo, playas, actividades...",
    "hero.explore": "Explorar",
    "hero.viewDiveSites": "Ver Sitios de Buceo",
    "hero.stats.diveSites": "Sitios de Buceo",
    "hero.stats.beaches": "Playas",
    "hero.stats.restaurants": "Restaurantes",
    "hero.stats.daysOfSun": "Días de Sol",
    
    // Dive Sites
    "diveSites.title": "Sitios de Buceo de Clase Mundial",
    "diveSites.description": "Explora más de 30 increíbles sitios de buceo alrededor de Koh Tao, desde arrecifes para principiantes hasta pináculos avanzados",
    "diveSites.featured": "Sitio Destacado",
    "diveSites.chumphonPinnacle": "Chumphon Pinnacle",
    "diveSites.chumphonDescription": "Uno de los sitios de buceo más famosos de Koh Tao, conocido por su rica vida marina y fuertes corrientes. Encuentra tiburones ballena, barracudas y meros gigantes.",
    "diveSites.bookDiveTrip": "Reservar Buceo",
    "diveSites.viewDetails": "Ver Detalles",
    "diveSites.exploreAll": "Explorar Todos los Sitios",
    "diveSites.difficulty.advanced": "Avanzado",
    "diveSites.difficulty.intermediate": "Intermedio",
    "diveSites.difficulty.beginner": "Principiante",
    "diveSites.depth": "Profundidad",
    "diveSites.marineLife": "Vida Marina",
    
    // Destinations
    "destinations.title": "Destinos Imperdibles",
    "destinations.description": "Desde playas prístinas hasta miradores impresionantes, descubre las ubicaciones más impresionantes de Koh Tao",
    "destinations.getDirections": "Obtener Direcciones",
    "destinations.mapTitle": "Explora con Mapa Interactivo",
    "destinations.mapDescription": "Navega Koh Tao con nuestro mapa integral que incluye todos los sitios de buceo, playas, restaurantes y actividades",
    "destinations.openMap": "Abrir Mapa Interactivo",
    "destinations.type.beach": "Playa",
    "destinations.type.viewpoint": "Mirador",
    "destinations.type.temple": "Templo",
    
    // Activities
    "activities.title": "Actividades y Experiencias",
    "activities.description": "Reserva experiencias y aventuras inolvidables en Koh Tao",
    "activities.bookNow": "Reservar Ahora",
    "activities.specialTitle": "Oferta Especial Anticipada",
    "activities.specialDescription": "Reserva tu curso de buceo o actividad con 7 días de anticipación y obtén 15% de descuento",
    "activities.viewAllDeals": "Ver Todas las Ofertas",
    
    // Accommodations
    "accommodations.title": "Alojamientos",
    "accommodations.description": "Encuentra el lugar perfecto para quedarte en Koh Tao, desde hostales económicos hasta resorts de lujo frente al mar",
    "accommodations.featured": "Alojamiento Destacado",
    "accommodations.bookNow": "Reservar Ahora",
    "accommodations.viewDetails": "Ver Detalles",
    "accommodations.exploreAll": "Explorar Todos los Alojamientos",
    "accommodations.type.resort": "Resort",
    "accommodations.type.villa": "Villa",
    "accommodations.type.bungalow": "Bungalow",
    "accommodations.type.hostel": "Hostal",
    "accommodations.pricePerNight": "/noche",
    
    // Business Directory
    "businessDirectory.title": "Directorio de Negocios",
    "businessDirectory.description": "Descubre restaurantes, tiendas, centros de buceo y servicios en Koh Tao",
    "businessDirectory.all": "Todos",
    "businessDirectory.restaurants": "Restaurantes",
    "businessDirectory.diveShops": "Tiendas de Buceo",
    "businessDirectory.shopping": "Compras",
    "businessDirectory.cafes": "Cafeterías",
    "businessDirectory.details": "Detalles",
    "businessDirectory.contact": "Contactar",
    "businessDirectory.viewAll": "Ver Todos los Negocios",
    
    // Newsletter
    "newsletter.title": "Mantente Actualizado",
    "newsletter.description": "Recibe las últimas noticias, ofertas exclusivas y consejos de viaje en tu bandeja de entrada",
    "newsletter.placeholder": "Ingresa tu dirección de correo",
    "newsletter.subscribe": "Suscribirse",
    "newsletter.subscribers": "Únete a más de 5,000 viajeros explorando Koh Tao",
    
    // Footer
    "footer.explore": "Explorar",
    "footer.activities": "Actividades",
    "footer.plan": "Planificar",
    "footer.about": "Acerca de",
    "footer.backToTop": "Volver Arriba",
    "footer.copyright": "© 2025 Koh Tao Guide. Todos los derechos reservados. Hecho con amor para viajeros.",
    "footer.description": "Tu compañero de viaje integral para explorar el paraíso tropical de Tailandia.",
    "footer.link.diveSites": "Sitios de Buceo",
    "footer.link.beaches": "Playas",
    "footer.link.viewpoints": "Miradores",
    "footer.link.restaurants": "Restaurantes",
    "footer.link.nightlife": "Vida Nocturna",
    "footer.link.divingCourses": "Cursos de Buceo",
    "footer.link.boatTours": "Tours en Barco",
    "footer.link.snorkeling": "Buceo con Snorkel",
    "footer.link.bikeRentals": "Alquiler de Bicicletas",
    "footer.link.islandHopping": "Salto de Islas",
    "footer.link.accommodations": "Alojamientos",
    "footer.link.gettingThere": "Cómo Llegar",
    "footer.link.bestTimeToVisit": "Mejor Época para Visitar",
    "footer.link.travelTips": "Consejos de Viaje",
    "footer.link.weather": "Clima",
    "footer.link.aboutUs": "Acerca de Nosotros",
    "footer.link.contact": "Contacto",
    "footer.link.businessListings": "Listados de Negocios",
    "footer.link.advertise": "Anunciar",
    "footer.link.termsPrivacy": "Términos y Privacidad",
    "footer.address": "Koh Tao, Surat Thani, Tailandia",
    
    // Toast Messages
    "toast.gettingDirections": "Obtener Direcciones",
    "toast.openingMap": "Abriendo mapa a",
    "toast.interactiveMap": "Mapa Interactivo",
    "toast.loadingMap": "Cargando mapa interactivo de Koh Tao...",
    "toast.bookingActivity": "Reservando Actividad",
    "toast.openingBooking": "Abriendo reserva para",
    "toast.specialDeals": "Ofertas Especiales",
    "toast.loadingDeals": "Cargando ofertas exclusivas y descuentos...",
    "toast.bookAccommodation": "Reservar Alojamiento",
    "toast.openingAccommodation": "Abriendo reserva para",
    "toast.openingDetails": "Abriendo información detallada...",
    "toast.allAccommodations": "Todos los Alojamientos",
    "toast.loadingAccommodations": "Cargando catálogo completo de alojamientos...",
    "toast.contactBusiness": "Contactar Negocio",
    "toast.openingContact": "Abriendo opciones de contacto para",
    "toast.allBusinesses": "Todos",
    "toast.loadingBusinesses": "Cargando directorio completo...",
    "toast.success": "¡Éxito!",
    "toast.subscribed": "Gracias por suscribirte a nuestro boletín.",
    
    // Destinations Data
    "destinations.saireeBeach.name": "Playa Sairee",
    "destinations.saireeBeach.description": "La playa más larga de Koh Tao, perfecta para nadar y ver atardeceres",
    "destinations.johnSuwan.name": "Mirador John-Suwan",
    "destinations.johnSuwan.description": "Vistas panorámicas impresionantes de 360° de la isla y el mar circundante",
    "destinations.sharkBay.name": "Bahía de Tiburones",
    "destinations.sharkBay.description": "Bahía apartada conocida por los tiburones de arrecife y excelente buceo con snorkel",
    "destinations.mangoViewpoint.name": "Mirador Mango",
    "destinations.mangoViewpoint.description": "Mirador popular con vistas impresionantes y un ambiente relajado",
    "destinations.nangYuanIsland.name": "Isla Nang Yuan",
    "destinations.nangYuanIsland.description": "Tres pequeños islotes conectados por un banco de arena, famosos por playas prístinas y excelente buceo con snorkel",
    "destinations.tanoteBay.name": "Bahía Tanote",
    "destinations.tanoteBay.description": "Aguas cristalinas y arrecifes de coral vibrantes, perfecto para entusiastas del buceo con snorkel y buceo",
    "destinations.saiNuanBeach.name": "Playa Sai Nuan",
    "destinations.saiNuanBeach.description": "Playa tranquila con arenas blancas suaves y aguas claras, ideal para nadar y relajarse",
    "destinations.aowLeukBeach.name": "Playa Aow Leuk",
    "destinations.aowLeukBeach.description": "Aguas claras y abundante vida marina hacen de este un lugar popular para buceo con snorkel",
    "destinations.watKohTao.name": "Wat Koh Tao",
    "destinations.watKohTao.description": "Wat Koh Charoen Santi Dhamma - Un sereno santuario budista fundado en 1977. Ubicado en el corazón de la isla, este templo ofrece a los visitantes una visión única de las prácticas espirituales y las enseñanzas budistas en un ambiente pacífico y tranquilo",
    "destinations.activity.swimming": "Natación",
    "destinations.activity.snorkeling": "Buceo con Snorkel",
    "destinations.activity.beachBars": "Bares en la Playa",
    "destinations.activity.photography": "Fotografía",
    "destinations.activity.sunsetWatching": "Ver Atardecer",
    "destinations.activity.hiking": "Senderismo",
    "destinations.activity.wildlifeWatching": "Observación de Vida Silvestre",
    "destinations.activity.relaxation": "Relajación",
    "destinations.activity.sunriseViews": "Vistas del Amanecer",
    "destinations.activity.islandHopping": "Salto de Islas",
    "destinations.activity.diving": "Buceo",
    "destinations.activity.culturalExploration": "Exploración Cultural",
    "destinations.activity.meditation": "Meditación",
    
    // Activities Data
    "activities.divingCourses.title": "Cursos de Buceo",
    "activities.divingCourses.description": "Desde principiante hasta niveles profesionales",
    "activities.divingCourses.feature.padi": "Certificado PADI",
    "activities.divingCourses.feature.deposit": "Reserva con 10% de Anticipo",
    "activities.divingCourses.feature.instructors": "Instructores Expertos",
    "activities.boatTours.title": "Tours en Barco",
    "activities.boatTours.description": "Salto de islas y viajes de buceo con snorkel",
    "activities.boatTours.feature.fullDay": "Tours de Día Completo",
    "activities.boatTours.feature.snorkelGear": "Equipo de Snorkel",
    "activities.boatTours.feature.lunch": "Almuerzo Incluido",
    "activities.bikeRentals.title": "Alquiler de Bicicletas",
    "activities.bikeRentals.description": "Explora la isla a tu propio ritmo",
    "activities.bikeRentals.feature.vehicles": "Scooters y Motocicletas",
    "activities.bikeRentals.feature.rates": "Tarifas Diarias y Semanales",
    "activities.bikeRentals.feature.helmet": "Casco Incluido",
    "activities.foodTours.title": "Tours Gastronómicos",
    "activities.foodTours.description": "Prueba la auténtica cocina tailandesa",
    "activities.foodTours.feature.restaurants": "Restaurantes Locales",
    "activities.foodTours.feature.streetFood": "Comida Callejera",
    "activities.foodTours.feature.cookingClasses": "Clases de Cocina",
    "activities.eventsParties.title": "Eventos y Fiestas",
    "activities.eventsParties.description": "Fiestas en la playa y eventos culturales",
    "activities.eventsParties.feature.fullMoon": "Fiestas de Luna Llena",
    "activities.eventsParties.feature.liveMusic": "Música en Vivo",
    "activities.eventsParties.feature.fireShows": "Espectáculos de Fuego",
    "activities.activityCalendar.title": "Calendario de Actividades",
    "activities.activityCalendar.description": "Planifica tu horario perfecto",
    "activities.activityCalendar.feature.events": "Próximos Eventos",
    "activities.activityCalendar.feature.book": "Reservar con Anticipación",
    "activities.activityCalendar.feature.deals": "Ofertas Especiales",
    
    // Accommodations Data
    "accommodations.oceanView.name": "Resort Vista al Océano",
    "accommodations.oceanView.description": "Experimenta la vida de lujo frente al mar con servicios de clase mundial y atardeceres impresionantes",
    "accommodations.taoBeach.name": "Resort Playa Tao",
    "accommodations.taoBeach.description": "Resort frente a la playa con impresionantes vistas al océano y fácil acceso a tiendas de buceo",
    "accommodations.diveInn.name": "Bungalows Dive Inn",
    "accommodations.diveInn.description": "Bungalows económicos perfectos para buzos, cerca de sitios de buceo",
    "accommodations.luxuryVilla.name": "Villa de Lujo en la Playa",
    "accommodations.luxuryVilla.description": "Villa premium frente a la playa con acceso privado y todos los servicios",
    "accommodations.backpackerHostel.name": "Hostal de Mochileros",
    "accommodations.backpackerHostel.description": "Ambiente acogedor de hostal con dormitorios compartidos y áreas comunes",
    "accommodations.location.saireeBeach": "Playa Sairee",
    "accommodations.location.chalokBaanKao": "Chalok Baan Kao",
    "accommodations.location.maeHaad": "Mae Haad",
    "accommodations.amenity.pool": "Piscina",
    "accommodations.amenity.restaurant": "Restaurante",
    "accommodations.amenity.wifi": "WiFi",
    "accommodations.amenity.ac": "Aire Acondicionado",
    "accommodations.amenity.fan": "Ventilador",
    "accommodations.amenity.sharedBathroom": "Baño Compartido",
    "accommodations.amenity.privateBeach": "Playa Privada",
    "accommodations.amenity.kitchen": "Cocina",
    "accommodations.amenity.sharedKitchen": "Cocina Compartida",
    "accommodations.amenity.commonArea": "Área Común",
    
    // Business Directory Data
    "businesses.saireeBeachRestaurant.name": "Restaurante Playa Sairee",
    "businesses.saireeBeachRestaurant.description": "Mariscos frescos y cocina tailandesa con vistas al océano",
    "businesses.diveShopPro.name": "Dive Shop Pro",
    "businesses.diveShopPro.description": "Centro de buceo de servicio completo con alquiler de equipo y cursos",
    "businesses.islandMarket.name": "Mercado de la Isla",
    "businesses.islandMarket.description": "Mercado local con souvenirs, ropa y artículos esenciales",
    "businesses.sunsetCafe.name": "Café Atardecer",
    "businesses.sunsetCafe.description": "Acogedor café con café, batidos y comidas ligeras",
    "businesses.thaiMassageSpa.name": "Spa de Masaje Tailandés",
    "businesses.thaiMassageSpa.description": "Masajes tailandeses tradicionales y servicios de spa",
    "businesses.beachBarGrill.name": "Bar y Parrilla en la Playa",
    "businesses.beachBarGrill.description": "Comida relajada junto al mar con cócteles y barbacoa",
    "businesses.diveGearStore.name": "Tienda de Equipo de Buceo",
    "businesses.diveGearStore.description": "Equipo profesional de buceo y accesorios",
    "businesses.organicJuiceBar.name": "Bar de Zumos Orgánicos",
    "businesses.organicJuiceBar.description": "Zumos frescos, bowls de batidos y snacks saludables",
    "businesses.location.saireeBeach": "Playa Sairee",
    "businesses.location.maeHaad": "Mae Haad",
    "businesses.location.chalokBaanKao": "Chalok Baan Kao",
    "businesses.category.restaurant": "Restaurante",
    "businesses.category.diveShop": "Tienda de Buceo",
    "businesses.category.shopping": "Compras",
    "businesses.category.cafe": "Cafetería",
    "businesses.category.spa": "Spa",
    
    // Reviews
    "reviews.customerReviews": "Reseñas de Clientes",
    "reviews.reviews": "reseñas",
    "reviews.writeReview": "Escribir una Reseña",
    "reviews.yourName": "Tu Nombre",
    "reviews.namePlaceholder": "Ingresa tu nombre",
    "reviews.rating": "Calificación",
    "reviews.comment": "Comentario",
    "reviews.commentPlaceholder": "Comparte tu experiencia...",
    "reviews.submitReview": "Enviar Reseña",
    "reviews.cancel": "Cancelar",
    "reviews.thankYou": "¡Gracias!",
    "reviews.reviewSubmitted": "Tu reseña ha sido enviada exitosamente.",
    "reviews.noReviews": "Aún no hay reseñas. ¡Sé el primero en reseñar!",
    "reviews.error": "Error",
    "reviews.fillAllFields": "Por favor completa todos los campos.",
    "destinations.viewDetails": "Ver Detalles",
  },
  th: {
    // Navigation
    "nav.diveSites": "จุดดำน้ำ",
    "nav.destinations": "สถานที่ท่องเที่ยว",
    "nav.activities": "กิจกรรม",
    "nav.accommodations": "ที่พัก",
    "nav.businessDirectory": "ไดเรกทอรีธุรกิจ",
    "nav.planTrip": "วางแผนเที่ยว",
    
    // Hero
    "hero.title": "ค้นพบ",
    "hero.subtitle": "เกาะเต่า",
    "hero.description": "คู่มือการท่องเที่ยวที่ดีที่สุดของคุณสำหรับสวรรค์การดำน้ำเขตร้อนของประเทศไทย สำรวจชายหาดอันบริสุทธิ์ จุดดำน้ำระดับโลก และการผจญภัยที่น่าจดจำ",
    "hero.searchPlaceholder": "ค้นหาจุดดำน้ำ ชายหาด กิจกรรม...",
    "hero.explore": "สำรวจ",
    "hero.viewDiveSites": "ดูจุดดำน้ำ",
    "hero.stats.diveSites": "จุดดำน้ำ",
    "hero.stats.beaches": "ชายหาด",
    "hero.stats.restaurants": "ร้านอาหาร",
    "hero.stats.daysOfSun": "วันแดด",
    
    // Dive Sites
    "diveSites.title": "จุดดำน้ำระดับโลก",
    "diveSites.description": "สำรวจจุดดำน้ำที่ยอดเยี่ยมมากกว่า 30 แห่งรอบเกาะเต่า จากแนวปะการังเหมาะสำหรับผู้เริ่มต้น ถึงยอดแหลมขั้นสูง",
    "diveSites.featured": "จุดดำน้ำแนะนำ",
    "diveSites.chumphonPinnacle": "ชุมพร พินนาเคิล",
    "diveSites.chumphonDescription": "หนึ่งในจุดดำน้ำที่มีชื่อเสียงที่สุดของเกาะเต่า รู้จักกันในเรื่องสัตว์ทะเลที่อุดมสมบูรณ์และกระแสน้ำที่แรง พบฉลามวาฬ ปลาสาก และปลาเก๋าขนาดใหญ่",
    "diveSites.bookDiveTrip": "จองทริปดำน้ำ",
    "diveSites.viewDetails": "ดูรายละเอียด",
    "diveSites.exploreAll": "สำรวจจุดดำน้ำทั้งหมด",
    "diveSites.difficulty.advanced": "ขั้นสูง",
    "diveSites.difficulty.intermediate": "ปานกลาง",
    "diveSites.difficulty.beginner": "เริ่มต้น",
    "diveSites.depth": "ความลึก",
    "diveSites.marineLife": "สัตว์ทะเล",
    
    // Destinations
    "destinations.title": "สถานที่ที่ต้องไปเยือน",
    "destinations.description": "ตั้งแต่ชายหาดอันบริสุทธิ์ไปจนถึงจุดชมวิวที่น่าตื่นตาตื่นใจ ค้นพบสถานที่ที่สวยงามที่สุดของเกาะเต่า",
    "destinations.getDirections": "ดูเส้นทาง",
    "destinations.mapTitle": "สำรวจด้วยแผนที่แบบโต้ตอบ",
    "destinations.mapDescription": "นำทางเกาะเต่าด้วยแผนที่ที่ครอบคลุมของเรารวมถึงจุดดำน้ำทั้งหมด ชายหาด ร้านอาหาร และกิจกรรม",
    "destinations.openMap": "เปิดแผนที่แบบโต้ตอบ",
    "destinations.type.beach": "ชายหาด",
    "destinations.type.viewpoint": "จุดชมวิว",
    "destinations.type.temple": "วัด",
    
    // Activities
    "activities.title": "กิจกรรมและประสบการณ์",
    "activities.description": "จองประสบการณ์และการผจญภัยที่น่าจดจำบนเกาะเต่า",
    "activities.bookNow": "จองเลย",
    "activities.specialTitle": "โปรโมชั่นจองล่วงหน้า",
    "activities.specialDescription": "จองหลักสูตรดำน้ำหรือกิจกรรมของคุณล่วงหน้า 7 วันและรับส่วนลด 15%",
    "activities.viewAllDeals": "ดูข้อเสนอทั้งหมด",
    
    // Accommodations
    "accommodations.title": "ที่พัก",
    "accommodations.description": "ค้นหาที่พักที่สมบูรณ์แบบบนเกาะเต่า ตั้งแต่โฮสเทลราคาประหยัดไปจนถึงรีสอร์ทริมชายหาดหรูหรา",
    "accommodations.featured": "ที่พักแนะนำ",
    "accommodations.bookNow": "จองเลย",
    "accommodations.viewDetails": "ดูรายละเอียด",
    "accommodations.exploreAll": "สำรวจที่พักทั้งหมด",
    "accommodations.type.resort": "รีสอร์ท",
    "accommodations.type.villa": "วิลล่า",
    "accommodations.type.bungalow": "บังกะโล",
    "accommodations.type.hostel": "โฮสเทล",
    "accommodations.pricePerNight": "/คืน",
    
    // Business Directory
    "businessDirectory.title": "ไดเรกทอรีธุรกิจ",
    "businessDirectory.description": "ค้นพบร้านอาหาร ร้านค้า ศูนย์ดำน้ำ และบริการทั่วเกาะเต่า",
    "businessDirectory.all": "ทั้งหมด",
    "businessDirectory.restaurants": "ร้านอาหาร",
    "businessDirectory.diveShops": "ร้านดำน้ำ",
    "businessDirectory.shopping": "ช้อปปิ้ง",
    "businessDirectory.cafes": "ร้านกาแฟ",
    "businessDirectory.details": "รายละเอียด",
    "businessDirectory.contact": "ติดต่อ",
    "businessDirectory.viewAll": "ดูธุรกิจทั้งหมด",
    
    // Newsletter
    "newsletter.title": "ติดตามข่าวสาร",
    "newsletter.description": "รับข่าวสารล่าสุด ข้อเสนอพิเศษ และเคล็ดลับการท่องเที่ยวส่งถึงกล่องจดหมายของคุณ",
    "newsletter.placeholder": "ใส่อีเมลของคุณ",
    "newsletter.subscribe": "สมัครสมาชิก",
    "newsletter.subscribers": "ร่วมกับนักท่องเที่ยวมากกว่า 5,000 คนที่สำรวจเกาะเต่า",
    
    // Footer
    "footer.explore": "สำรวจ",
    "footer.activities": "กิจกรรม",
    "footer.plan": "วางแผน",
    "footer.about": "เกี่ยวกับ",
    "footer.backToTop": "กลับด้านบน",
    "footer.copyright": "© 2025 Koh Tao Guide สงวนลิขสิทธิ์ สร้างด้วยความรักสำหรับนักท่องเที่ยว",
    "footer.description": "เพื่อนร่วมเดินทางที่ครอบคลุมของคุณสำหรับสำรวจสวรรค์เขตร้อนของประเทศไทย",
    "footer.link.diveSites": "จุดดำน้ำ",
    "footer.link.beaches": "ชายหาด",
    "footer.link.viewpoints": "จุดชมวิว",
    "footer.link.restaurants": "ร้านอาหาร",
    "footer.link.nightlife": "ไนท์ไลฟ์",
    "footer.link.divingCourses": "คอร์สเรียนดำน้ำ",
    "footer.link.boatTours": "ทัวร์เรือ",
    "footer.link.snorkeling": "ดำน้ำตื้น",
    "footer.link.bikeRentals": "เช่าจักรยาน",
    "footer.link.islandHopping": "เที่ยวเกาะ",
    "footer.link.accommodations": "ที่พัก",
    "footer.link.gettingThere": "วิธีเดินทาง",
    "footer.link.bestTimeToVisit": "ช่วงเวลาที่ดีที่สุดในการเที่ยว",
    "footer.link.travelTips": "เคล็ดลับการท่องเที่ยว",
    "footer.link.weather": "สภาพอากาศ",
    "footer.link.aboutUs": "เกี่ยวกับเรา",
    "footer.link.contact": "ติดต่อ",
    "footer.link.businessListings": "รายชื่อธุรกิจ",
    "footer.link.advertise": "โฆษณา",
    "footer.link.termsPrivacy": "ข้อกำหนดและความเป็นส่วนตัว",
    "footer.address": "เกาะเต่า สุราษฎร์ธานี ประเทศไทย",
    
    // Toast Messages
    "toast.gettingDirections": "ดูเส้นทาง",
    "toast.openingMap": "กำลังเปิดแผนที่ไปที่",
    "toast.interactiveMap": "แผนที่แบบโต้ตอบ",
    "toast.loadingMap": "กำลังโหลดแผนที่แบบโต้ตอบของเกาะเต่า...",
    "toast.bookingActivity": "กำลังจองกิจกรรม",
    "toast.openingBooking": "กำลังเปิดการจองสำหรับ",
    "toast.specialDeals": "ข้อเสนอพิเศษ",
    "toast.loadingDeals": "กำลังโหลดข้อเสนอพิเศษและส่วนลด...",
    "toast.bookAccommodation": "จองที่พัก",
    "toast.openingAccommodation": "กำลังเปิดการจองสำหรับ",
    "toast.openingDetails": "กำลังเปิดข้อมูลรายละเอียด...",
    "toast.allAccommodations": "ที่พักทั้งหมด",
    "toast.loadingAccommodations": "กำลังโหลดแคตตาล็อกที่พักทั้งหมด...",
    "toast.contactBusiness": "ติดต่อธุรกิจ",
    "toast.openingContact": "กำลังเปิดตัวเลือกติดต่อสำหรับ",
    "toast.allBusinesses": "ทั้งหมด",
    "toast.loadingBusinesses": "กำลังโหลดไดเรกทอรีทั้งหมด...",
    "toast.success": "สำเร็จ!",
    "toast.subscribed": "ขอบคุณสำหรับการสมัครรับจดหมายข่าวของเรา",
    
    // Destinations Data
    "destinations.saireeBeach.name": "หาดไทรี",
    "destinations.saireeBeach.description": "หาดที่ยาวที่สุดในเกาะเต่า เหมาะสำหรับการว่ายน้ำและการชมพระอาทิตย์ตก",
    "destinations.johnSuwan.name": "จุดชมวิวจอห์น-สุวรรณ",
    "destinations.johnSuwan.description": "มุมมองแบบ 360 องศาที่น่าตื่นตาตื่นใจของเกาะและทะเลโดยรอบ",
    "destinations.sharkBay.name": "อ่าวฉลาม",
    "destinations.sharkBay.description": "อ่าวที่เงียบสงบ ขึ้นชื่อเรื่องฉลามปะการังและกิจกรรมดำน้ำตื้นที่ยอดเยี่ยม",
    "destinations.mangoViewpoint.name": "จุดชมวิวมะม่วง",
    "destinations.mangoViewpoint.description": "จุดชมวิวยอดนิยมพร้อมทิวทัศน์ที่สวยงามและบรรยากาศผ่อนคลาย",
    "destinations.nangYuanIsland.name": "เกาะนางยวน",
    "destinations.nangYuanIsland.description": "เกาะเล็กสามเกาะที่เชื่อมต่อกันด้วยสันทราย มีชื่อเสียงเรื่องหาดทรายที่สวยงามและการดำน้ำตื้นที่ยอดเยี่ยม",
    "destinations.tanoteBay.name": "อ่าวตะนอต",
    "destinations.tanoteBay.description": "น้ำใสและปะการังที่สวยงาม เหมาะสำหรับผู้ที่ชื่นชอบการดำน้ำตื้นและการดำน้ำ",
    "destinations.saiNuanBeach.name": "หาดทรายนวล",
    "destinations.saiNuanBeach.description": "หาดทรายที่เงียบสงบพร้อมทรายขาวนุ่มและน้ำใส เหมาะสำหรับการว่ายน้ำและการพักผ่อน",
    "destinations.aowLeukBeach.name": "หาดอ่าวลึก",
    "destinations.aowLeukBeach.description": "น้ำใสและสัตว์ทะเลที่อุดมสมบูรณ์ ทำให้ที่นี่เป็นจุดดำน้ำตื้นยอดนิยม",
    "destinations.watKohTao.name": "วัดเกาะเต่า",
    "destinations.watKohTao.description": "วัดเกาะเจริญสันติธรรม - สถานที่ศักดิ์สิทธิ์ทางพุทธศาสนาที่เงียบสงบ ก่อตั้งขึ้นในปี 1977 ตั้งอยู่ในใจกลางเกาะ วัดแห่งนี้ให้ผู้เยี่ยมชมได้เห็นภาพรวมของแนวปฏิบัติทางจิตวิญญาณและคำสอนทางพุทธศาสนาในบรรยากาศที่สงบและเงียบสงบ",
    "destinations.activity.swimming": "ว่ายน้ำ",
    "destinations.activity.snorkeling": "ดำน้ำตื้น",
    "destinations.activity.beachBars": "บาร์ริมชายหาด",
    "destinations.activity.photography": "ถ่ายภาพ",
    "destinations.activity.sunsetWatching": "ชมพระอาทิตย์ตก",
    "destinations.activity.hiking": "เดินป่า",
    "destinations.activity.wildlifeWatching": "ดูสัตว์ป่า",
    "destinations.activity.relaxation": "ผ่อนคลาย",
    "destinations.activity.sunriseViews": "ชมพระอาทิตย์ขึ้น",
    "destinations.activity.islandHopping": "ท่องเที่ยวเกาะ",
    "destinations.activity.diving": "ดำน้ำ",
    "destinations.activity.culturalExploration": "สำรวจวัฒนธรรม",
    "destinations.activity.meditation": "นั่งสมาธิ",
    
    // Activities Data
    "activities.divingCourses.title": "คอร์สเรียนดำน้ำ",
    "activities.divingCourses.description": "ตั้งแต่ระดับเริ่มต้นถึงมืออาชีพ",
    "activities.divingCourses.feature.padi": "รับรอง PADI",
    "activities.divingCourses.feature.deposit": "จองด้วยเงินมัดจำ 10%",
    "activities.divingCourses.feature.instructors": "ผู้สอนผู้เชี่ยวชาญ",
    "activities.boatTours.title": "ทัวร์เรือ",
    "activities.boatTours.description": "เที่ยวเกาะและการดำน้ำตื้น",
    "activities.boatTours.feature.fullDay": "ทัวร์เต็มวัน",
    "activities.boatTours.feature.snorkelGear": "อุปกรณ์ดำน้ำตื้น",
    "activities.boatTours.feature.lunch": "รวมอาหารกลางวัน",
    "activities.bikeRentals.title": "เช่าจักรยาน",
    "activities.bikeRentals.description": "สำรวจเกาะตามจังหวะของคุณเอง",
    "activities.bikeRentals.feature.vehicles": "สกู๊ตเตอร์และรถจักรยานยนต์",
    "activities.bikeRentals.feature.rates": "อัตรารายวันและรายสัปดาห์",
    "activities.bikeRentals.feature.helmet": "รวมหมวกกันน็อค",
    "activities.foodTours.title": "ทัวร์อาหาร",
    "activities.foodTours.description": "ลิ้มลองอาหารไทยแท้",
    "activities.foodTours.feature.restaurants": "ร้านอาหารท้องถิ่น",
    "activities.foodTours.feature.streetFood": "อาหารริมทาง",
    "activities.foodTours.feature.cookingClasses": "คลาสเรียนทำอาหาร",
    "activities.eventsParties.title": "งานอีเวนต์และปาร์ตี้",
    "activities.eventsParties.description": "ปาร์ตี้ชายหาดและงานวัฒนธรรม",
    "activities.eventsParties.feature.fullMoon": "ปาร์ตี้พระจันทร์เต็มดวง",
    "activities.eventsParties.feature.liveMusic": "ดนตรีสด",
    "activities.eventsParties.feature.fireShows": "โชว์ไฟ",
    "activities.activityCalendar.title": "ปฏิทินกิจกรรม",
    "activities.activityCalendar.description": "วางแผนตารางเวลาที่สมบูรณ์แบบของคุณ",
    "activities.activityCalendar.feature.events": "กิจกรรมที่จะมาถึง",
    "activities.activityCalendar.feature.book": "จองล่วงหน้า",
    "activities.activityCalendar.feature.deals": "ข้อเสนอพิเศษ",
    
    // Accommodations Data
    "accommodations.oceanView.name": "รีสอร์ทวิวทะเล",
    "accommodations.oceanView.description": "สัมผัสการใช้ชีวิตริมชายหาดสุดหรูพร้อมสิ่งอำนวยความสะดวกระดับโลกและพระอาทิตย์ตกที่สวยงาม",
    "accommodations.taoBeach.name": "รีสอร์ทหาดเต่า",
    "accommodations.taoBeach.description": "รีสอร์ทริมชายหาดพร้อมวิวทะเลที่สวยงามและเข้าถึงร้านดำน้ำได้ง่าย",
    "accommodations.diveInn.name": "บังกะโลไดฟ์อินน์",
    "accommodations.diveInn.description": "บังกะโลราคาประหยัดเหมาะสำหรับนักดำน้ำ ใกล้จุดดำน้ำ",
    "accommodations.luxuryVilla.name": "วิลล่าหาดหรูหรา",
    "accommodations.luxuryVilla.description": "วิลล่าหาดพรีเมียมพร้อมการเข้าถึงส่วนตัวและสิ่งอำนวยความสะดวกครบครัน",
    "accommodations.backpackerHostel.name": "โฮสเทลแบ็กแพ็คเกอร์",
    "accommodations.backpackerHostel.description": "บรรยากาศโฮสเทลที่เป็นมิตรพร้อมห้องนอนรวมและพื้นที่ส่วนกลาง",
    "accommodations.location.saireeBeach": "หาดไทรี",
    "accommodations.location.chalokBaanKao": "เฉลิมบันเกา",
    "accommodations.location.maeHaad": "แม่หาด",
    "accommodations.amenity.pool": "สระว่ายน้ำ",
    "accommodations.amenity.restaurant": "ร้านอาหาร",
    "accommodations.amenity.wifi": "WiFi",
    "accommodations.amenity.ac": "เครื่องปรับอากาศ",
    "accommodations.amenity.fan": "พัดลม",
    "accommodations.amenity.sharedBathroom": "ห้องน้ำรวม",
    "accommodations.amenity.privateBeach": "หาดส่วนตัว",
    "accommodations.amenity.kitchen": "ห้องครัว",
    "accommodations.amenity.sharedKitchen": "ห้องครัวรวม",
    "accommodations.amenity.commonArea": "พื้นที่ส่วนกลาง",
    
    // Business Directory Data
    "businesses.saireeBeachRestaurant.name": "ร้านอาหารหาดไทรี",
    "businesses.saireeBeachRestaurant.description": "อาหารทะเลสดและอาหารไทยพร้อมวิวทะเล",
    "businesses.diveShopPro.name": "ไดฟ์ช็อปโปร",
    "businesses.diveShopPro.description": "ศูนย์ดำน้ำแบบครบวงจรพร้อมให้เช่าอุปกรณ์และคอร์สเรียน",
    "businesses.islandMarket.name": "ตลาดเกาะ",
    "businesses.islandMarket.description": "ตลาดท้องถิ่นพร้อมของที่ระลึก เสื้อผ้า และของใช้จำเป็น",
    "businesses.sunsetCafe.name": "คาเฟ่ซันเซ็ต",
    "businesses.sunsetCafe.description": "คาเฟ่ที่อบอุ่นพร้อมกาแฟ น้ำปั่น และอาหารเบาๆ",
    "businesses.thaiMassageSpa.name": "สปานวดไทย",
    "businesses.thaiMassageSpa.description": "การนวดไทยแบบดั้งเดิมและบริการสปา",
    "businesses.beachBarGrill.name": "บาร์และกริลล์ริมหาด",
    "businesses.beachBarGrill.description": "ร้านอาหารริมชายหาดที่ผ่อนคลายพร้อมค็อกเทลและบาร์บีคิว",
    "businesses.diveGearStore.name": "ร้านอุปกรณ์ดำน้ำ",
    "businesses.diveGearStore.description": "อุปกรณ์ดำน้ำมืออาชีพและอุปกรณ์เสริม",
    "businesses.organicJuiceBar.name": "บาร์น้ำผลไม้ออร์แกนิก",
    "businesses.organicJuiceBar.description": "น้ำผลไม้สด ชามสมูทตี้ และของว่างเพื่อสุขภาพ",
    "businesses.location.saireeBeach": "หาดไทรี",
    "businesses.location.maeHaad": "แม่หาด",
    "businesses.location.chalokBaanKao": "เฉลิมบันเกา",
    "businesses.category.restaurant": "ร้านอาหาร",
    "businesses.category.diveShop": "ร้านดำน้ำ",
    "businesses.category.shopping": "ช้อปปิ้ง",
    "businesses.category.cafe": "ร้านกาแฟ",
    "businesses.category.spa": "สปา",
    
    // Reviews
    "reviews.customerReviews": "รีวิวจากลูกค้า",
    "reviews.reviews": "รีวิว",
    "reviews.writeReview": "เขียนรีวิว",
    "reviews.yourName": "ชื่อของคุณ",
    "reviews.namePlaceholder": "ใส่ชื่อของคุณ",
    "reviews.rating": "คะแนน",
    "reviews.comment": "ความคิดเห็น",
    "reviews.commentPlaceholder": "แบ่งปันประสบการณ์ของคุณ...",
    "reviews.submitReview": "ส่งรีวิว",
    "reviews.cancel": "ยกเลิก",
    "reviews.thankYou": "ขอบคุณ!",
    "reviews.reviewSubmitted": "รีวิวของคุณถูกส่งเรียบร้อยแล้ว",
    "reviews.noReviews": "ยังไม่มีรีวิว เป็นคนแรกที่รีวิว!",
    "reviews.error": "ข้อผิดพลาด",
    "reviews.fillAllFields": "กรุณากรอกข้อมูลทั้งหมด",
    "destinations.viewDetails": "ดูรายละเอียด",
  },
  de: {
    // Navigation
    "nav.diveSites": "Tauchplätze",
    "nav.destinations": "Reiseziele",
    "nav.activities": "Aktivitäten",
    "nav.accommodations": "Unterkünfte",
    "nav.businessDirectory": "Firmenverzeichnis",
    "nav.planTrip": "Reise planen",
    
    // Hero
    "hero.title": "Entdecke",
    "hero.subtitle": "Koh Tao",
    "hero.description": "Ihr ultimativer Reiseführer für Thailands tropisches Tauchparadies. Erkunden Sie unberührte Strände, erstklassige Tauchplätze und unvergessliche Abenteuer.",
    "hero.searchPlaceholder": "Tauchplätze, Strände, Aktivitäten suchen...",
    "hero.explore": "Erkunden",
    "hero.viewDiveSites": "Tauchplätze anzeigen",
    "hero.stats.diveSites": "Tauchplätze",
    "hero.stats.beaches": "Strände",
    "hero.stats.restaurants": "Restaurants",
    "hero.stats.daysOfSun": "Sonnentage",
    
    // Dive Sites
    "diveSites.title": "Weltklasse Tauchplätze",
    "diveSites.description": "Erkunden Sie über 30 unglaubliche Tauchplätze rund um Koh Tao, von anfängerfreundlichen Riffen bis hin zu fortgeschrittenen Pinnacles",
    "diveSites.featured": "Empfohlener Tauchplatz",
    "diveSites.chumphonPinnacle": "Chumphon Pinnacle",
    "diveSites.chumphonDescription": "Einer der berühmtesten Tauchplätze von Koh Tao, bekannt für seine reiche Meeresfauna und starke Strömungen. Begegnen Sie Walhaien, Barrakudas und riesigen Zackenbarschen.",
    "diveSites.bookDiveTrip": "Tauchtour buchen",
    "diveSites.viewDetails": "Details anzeigen",
    "diveSites.exploreAll": "Alle Tauchplätze erkunden",
    "diveSites.difficulty.advanced": "Fortgeschritten",
    "diveSites.difficulty.intermediate": "Mittel",
    "diveSites.difficulty.beginner": "Anfänger",
    "diveSites.depth": "Tiefe",
    "diveSites.marineLife": "Meeresfauna",
    
    // Destinations
    "destinations.title": "Sehenswürdigkeiten",
    "destinations.description": "Von unberührten Stränden bis hin zu atemberaubenden Aussichtspunkten - entdecken Sie die beeindruckendsten Orte auf Koh Tao",
    "destinations.getDirections": "Wegbeschreibung",
    "destinations.mapTitle": "Mit interaktiver Karte erkunden",
    "destinations.mapDescription": "Navigieren Sie durch Koh Tao mit unserer umfassenden Karte, die alle Tauchplätze, Strände, Restaurants und Aktivitäten zeigt",
    "destinations.openMap": "Interaktive Karte öffnen",
    "destinations.type.beach": "Strand",
    "destinations.type.viewpoint": "Aussichtspunkt",
    "destinations.type.temple": "Tempel",
    
    // Activities
    "activities.title": "Aktivitäten & Erlebnisse",
    "activities.description": "Buchen Sie unvergessliche Erlebnisse und Abenteuer auf Koh Tao",
    "activities.bookNow": "Jetzt buchen",
    "activities.specialTitle": "Frühbucher-Special",
    "activities.specialDescription": "Buchen Sie Ihren Tauchkurs oder Ihre Aktivität 7 Tage im Voraus und erhalten Sie 15% Rabatt",
    "activities.viewAllDeals": "Alle Angebote anzeigen",
    
    // Accommodations
    "accommodations.title": "Unterkünfte",
    "accommodations.description": "Finden Sie den perfekten Ort zum Übernachten auf Koh Tao, von preiswerten Hostels bis hin zu luxuriösen Strandresorts",
    "accommodations.featured": "Empfohlene Unterkunft",
    "accommodations.bookNow": "Jetzt buchen",
    "accommodations.viewDetails": "Details anzeigen",
    "accommodations.exploreAll": "Alle Unterkünfte erkunden",
    "accommodations.type.resort": "Resort",
    "accommodations.type.villa": "Villa",
    "accommodations.type.bungalow": "Bungalow",
    "accommodations.type.hostel": "Hostel",
    "accommodations.pricePerNight": "/Nacht",
    
    // Business Directory
    "businessDirectory.title": "Firmenverzeichnis",
    "businessDirectory.description": "Entdecken Sie Restaurants, Geschäfte, Tauchzentren und Dienstleistungen auf Koh Tao",
    "businessDirectory.all": "Alle",
    "businessDirectory.restaurants": "Restaurants",
    "businessDirectory.diveShops": "Tauchgeschäfte",
    "businessDirectory.shopping": "Einkaufen",
    "businessDirectory.cafes": "Cafés",
    "businessDirectory.details": "Details",
    "businessDirectory.contact": "Kontakt",
    "businessDirectory.viewAll": "Alle Unternehmen anzeigen",
    
    // Newsletter
    "newsletter.title": "Bleiben Sie informiert",
    "newsletter.description": "Erhalten Sie die neuesten Nachrichten, exklusive Angebote und Reisetipps direkt in Ihr Postfach",
    "newsletter.placeholder": "Geben Sie Ihre E-Mail-Adresse ein",
    "newsletter.subscribe": "Abonnieren",
    "newsletter.subscribers": "Schließen Sie sich über 5.000 Reisenden an, die Koh Tao erkunden",
    
    // Footer
    "footer.explore": "Erkunden",
    "footer.activities": "Aktivitäten",
    "footer.plan": "Planen",
    "footer.about": "Über uns",
    "footer.backToTop": "Nach oben",
    "footer.copyright": "© 2025 Koh Tao Guide. Alle Rechte vorbehalten. Mit Liebe für Reisende erstellt.",
    "footer.description": "Ihr umfassender Reisebegleiter für die Erkundung von Thailands tropischem Paradies.",
    "footer.link.diveSites": "Tauchplätze",
    "footer.link.beaches": "Strände",
    "footer.link.viewpoints": "Aussichtspunkte",
    "footer.link.restaurants": "Restaurants",
    "footer.link.nightlife": "Nachtleben",
    "footer.link.divingCourses": "Tauchkurse",
    "footer.link.boatTours": "Bootstouren",
    "footer.link.snorkeling": "Schnorcheln",
    "footer.link.bikeRentals": "Fahrradverleih",
    "footer.link.islandHopping": "Inselhopping",
    "footer.link.accommodations": "Unterkünfte",
    "footer.link.gettingThere": "Anreise",
    "footer.link.bestTimeToVisit": "Beste Reisezeit",
    "footer.link.travelTips": "Reisetipps",
    "footer.link.weather": "Wetter",
    "footer.link.aboutUs": "Über uns",
    "footer.link.contact": "Kontakt",
    "footer.link.businessListings": "Firmenverzeichnis",
    "footer.link.advertise": "Werbung",
    "footer.link.termsPrivacy": "AGB & Datenschutz",
    "footer.address": "Koh Tao, Surat Thani, Thailand",
    
    // Toast Messages
    "toast.gettingDirections": "Wegbeschreibung abrufen",
    "toast.openingMap": "Karte öffnen für",
    "toast.interactiveMap": "Interaktive Karte",
    "toast.loadingMap": "Interaktive Karte von Koh Tao wird geladen...",
    "toast.bookingActivity": "Aktivität buchen",
    "toast.openingBooking": "Buchung öffnen für",
    "toast.specialDeals": "Sonderangebote",
    "toast.loadingDeals": "Exklusive Angebote und Rabatte werden geladen...",
    "toast.bookAccommodation": "Unterkunft buchen",
    "toast.openingAccommodation": "Buchung öffnen für",
    "toast.openingDetails": "Detaillierte Informationen werden geöffnet...",
    "toast.allAccommodations": "Alle Unterkünfte",
    "toast.loadingAccommodations": "Vollständiger Unterkunftskatalog wird geladen...",
    "toast.contactBusiness": "Unternehmen kontaktieren",
    "toast.openingContact": "Kontaktoptionen öffnen für",
    "toast.allBusinesses": "Alle",
    "toast.loadingBusinesses": "Vollständiges Verzeichnis wird geladen...",
    "toast.success": "Erfolg!",
    "toast.subscribed": "Vielen Dank für Ihr Abonnement unseres Newsletters.",
    
    // Destinations Data
    "destinations.saireeBeach.name": "Sairee Beach",
    "destinations.saireeBeach.description": "Der längste Strand auf Koh Tao, perfekt zum Schwimmen und für Sonnenuntergänge",
    "destinations.johnSuwan.name": "John-Suwan Aussichtspunkt",
    "destinations.johnSuwan.description": "Atemberaubende 360° Panoramablicke auf die Insel und das umliegende Meer",
    "destinations.sharkBay.name": "Shark Bay",
    "destinations.sharkBay.description": "Abgelegene Bucht, bekannt für Schwarzspitzen-Riffhaie und ausgezeichnetes Schnorcheln",
    "destinations.mangoViewpoint.name": "Mango Aussichtspunkt",
    "destinations.mangoViewpoint.description": "Beliebter Aussichtspunkt mit atemberaubenden Ausblicken und entspannter Atmosphäre",
    "destinations.nangYuanIsland.name": "Nang Yuan Insel",
    "destinations.nangYuanIsland.description": "Drei kleine Inseln, die durch eine Sandbank verbunden sind, berühmt für unberührte Strände und ausgezeichnetes Schnorcheln",
    "destinations.tanoteBay.name": "Tanote Bucht",
    "destinations.tanoteBay.description": "Kristallklares Wasser und lebendige Korallenriffe, perfekt für Schnorchel- und Tauchbegeisterte",
    "destinations.saiNuanBeach.name": "Sai Nuan Strand",
    "destinations.saiNuanBeach.description": "Ruhiger Strand mit weichem weißen Sand und klarem Wasser, ideal zum Schwimmen und Entspannen",
    "destinations.aowLeukBeach.name": "Aow Leuk Strand",
    "destinations.aowLeukBeach.description": "Klares Wasser und reichhaltiges Meeresleben machen dies zu einem beliebten Schnorchelplatz",
    "destinations.watKohTao.name": "Wat Koh Tao",
    "destinations.watKohTao.description": "Wat Koh Charoen Santi Dhamma - Ein friedliches buddhistisches Heiligtum, gegründet 1977. Eingebettet im Herzen der Insel bietet dieser Tempel Besuchern einen einzigartigen Einblick in spirituelle Praktiken und buddhistische Lehren in einer friedlichen, ruhigen Umgebung",
    "destinations.activity.swimming": "Schwimmen",
    "destinations.activity.snorkeling": "Schnorcheln",
    "destinations.activity.beachBars": "Strandbars",
    "destinations.activity.photography": "Fotografie",
    "destinations.activity.sunsetWatching": "Sonnenuntergang beobachten",
    "destinations.activity.hiking": "Wandern",
    "destinations.activity.wildlifeWatching": "Wildtierbeobachtung",
    "destinations.activity.relaxation": "Entspannung",
    "destinations.activity.sunriseViews": "Sonnenaufgang",
    "destinations.activity.islandHopping": "Inselhopping",
    "destinations.activity.diving": "Tauchen",
    "destinations.activity.culturalExploration": "Kulturelle Erkundung",
    "destinations.activity.meditation": "Meditation",
    
    // Activities Data
    "activities.divingCourses.title": "Tauchkurse",
    "activities.divingCourses.description": "Von Anfänger bis Profi",
    "activities.divingCourses.feature.padi": "PADI zertifiziert",
    "activities.divingCourses.feature.deposit": "Buchung mit 10% Anzahlung",
    "activities.divingCourses.feature.instructors": "Erfahrene Instruktoren",
    "activities.boatTours.title": "Bootstouren",
    "activities.boatTours.description": "Inselhopping und Schnorcheltouren",
    "activities.boatTours.feature.fullDay": "Ganztagestouren",
    "activities.boatTours.feature.snorkelGear": "Schnorchelausrüstung",
    "activities.boatTours.feature.lunch": "Mittagessen inklusive",
    "activities.bikeRentals.title": "Fahrradverleih",
    "activities.bikeRentals.description": "Erkunden Sie die Insel in Ihrem eigenen Tempo",
    "activities.bikeRentals.feature.vehicles": "Roller & Motorräder",
    "activities.bikeRentals.feature.rates": "Tages- & Wochenpreise",
    "activities.bikeRentals.feature.helmet": "Helm inklusive",
    "activities.foodTours.title": "Kulinarische Touren",
    "activities.foodTours.description": "Probieren Sie authentische thailändische Küche",
    "activities.foodTours.feature.restaurants": "Lokale Restaurants",
    "activities.foodTours.feature.streetFood": "Street Food",
    "activities.foodTours.feature.cookingClasses": "Kochkurse",
    "activities.eventsParties.title": "Events & Partys",
    "activities.eventsParties.description": "Strandpartys und kulturelle Veranstaltungen",
    "activities.eventsParties.feature.fullMoon": "Vollmond-Partys",
    "activities.eventsParties.feature.liveMusic": "Live-Musik",
    "activities.eventsParties.feature.fireShows": "Feuershows",
    "activities.activityCalendar.title": "Aktivitätskalender",
    "activities.activityCalendar.description": "Planen Sie Ihren perfekten Zeitplan",
    "activities.activityCalendar.feature.events": "Anstehende Veranstaltungen",
    "activities.activityCalendar.feature.book": "Im Voraus buchen",
    "activities.activityCalendar.feature.deals": "Sonderangebote",
    
    // Accommodations Data
    "accommodations.oceanView.name": "Ocean View Resort",
    "accommodations.oceanView.description": "Erleben Sie luxuriöses Leben am Strand mit erstklassigen Annehmlichkeiten und atemberaubenden Sonnenuntergängen",
    "accommodations.taoBeach.name": "Tao Beach Resort",
    "accommodations.taoBeach.description": "Strandresort mit atemberaubendem Meerblick und einfachem Zugang zu Tauchgeschäften",
    "accommodations.diveInn.name": "Dive Inn Bungalows",
    "accommodations.diveInn.description": "Preiswerte Bungalows, perfekt für Taucher, in der Nähe von Tauchplätzen",
    "accommodations.luxuryVilla.name": "Luxus Strandvilla",
    "accommodations.luxuryVilla.description": "Premium Strandvilla mit privatem Zugang und vollständigen Annehmlichkeiten",
    "accommodations.backpackerHostel.name": "Backpacker Hostel",
    "accommodations.backpackerHostel.description": "Freundliche Hostel-Atmosphäre mit Gemeinschaftsräumen und Gemeinschaftsbereichen",
    "accommodations.location.saireeBeach": "Sairee Beach",
    "accommodations.location.chalokBaanKao": "Chalok Baan Kao",
    "accommodations.location.maeHaad": "Mae Haad",
    "accommodations.amenity.pool": "Pool",
    "accommodations.amenity.restaurant": "Restaurant",
    "accommodations.amenity.wifi": "WiFi",
    "accommodations.amenity.ac": "Klimaanlage",
    "accommodations.amenity.fan": "Ventilator",
    "accommodations.amenity.sharedBathroom": "Gemeinschaftsbad",
    "accommodations.amenity.privateBeach": "Privater Strand",
    "accommodations.amenity.kitchen": "Küche",
    "accommodations.amenity.sharedKitchen": "Gemeinschaftsküche",
    "accommodations.amenity.commonArea": "Gemeinschaftsbereich",
    
    // Business Directory Data
    "businesses.saireeBeachRestaurant.name": "Sairee Beach Restaurant",
    "businesses.saireeBeachRestaurant.description": "Frische Meeresfrüchte und thailändische Küche mit Meerblick",
    "businesses.diveShopPro.name": "Dive Shop Pro",
    "businesses.diveShopPro.description": "Vollständiges Tauchzentrum mit Ausrüstungsverleih und Kursen",
    "businesses.islandMarket.name": "Inselmarkt",
    "businesses.islandMarket.description": "Lokaler Markt mit Souvenirs, Kleidung und Grundbedarfsartikeln",
    "businesses.sunsetCafe.name": "Sunset Café",
    "businesses.sunsetCafe.description": "Gemütliches Café mit Kaffee, Smoothies und leichten Mahlzeiten",
    "businesses.thaiMassageSpa.name": "Thai Massage Spa",
    "businesses.thaiMassageSpa.description": "Traditionelle thailändische Massage und Spa-Services",
    "businesses.beachBarGrill.name": "Beach Bar & Grill",
    "businesses.beachBarGrill.description": "Entspanntes Strandrestaurant mit Cocktails und BBQ",
    "businesses.diveGearStore.name": "Tauchausrüstungsladen",
    "businesses.diveGearStore.description": "Professionelle Tauchausrüstung und Zubehör",
    "businesses.organicJuiceBar.name": "Bio-Saftbar",
    "businesses.organicJuiceBar.description": "Frische Säfte, Smoothie-Bowls und gesunde Snacks",
    "businesses.location.saireeBeach": "Sairee Beach",
    "businesses.location.maeHaad": "Mae Haad",
    "businesses.location.chalokBaanKao": "Chalok Baan Kao",
    "businesses.category.restaurant": "Restaurant",
    "businesses.category.diveShop": "Tauchgeschäft",
    "businesses.category.shopping": "Einkaufen",
    "businesses.category.cafe": "Café",
    "businesses.category.spa": "Spa",
    
    // Reviews
    "reviews.customerReviews": "Kundenbewertungen",
    "reviews.reviews": "Bewertungen",
    "reviews.writeReview": "Bewertung schreiben",
    "reviews.yourName": "Ihr Name",
    "reviews.namePlaceholder": "Geben Sie Ihren Namen ein",
    "reviews.rating": "Bewertung",
    "reviews.comment": "Kommentar",
    "reviews.commentPlaceholder": "Teilen Sie Ihre Erfahrung...",
    "reviews.submitReview": "Bewertung absenden",
    "reviews.cancel": "Abbrechen",
    "reviews.thankYou": "Vielen Dank!",
    "reviews.reviewSubmitted": "Ihre Bewertung wurde erfolgreich übermittelt.",
    "reviews.noReviews": "Noch keine Bewertungen. Seien Sie der Erste!",
    "reviews.error": "Fehler",
    "reviews.fillAllFields": "Bitte füllen Sie alle Felder aus.",
    "destinations.viewDetails": "Details anzeigen",
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "en";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

